import 'package:flutter/material.dart';
import 'package:google_fonts/google_fonts.dart';
import 'package:zimdoctors/models/doctor.dart';
import 'package:zimdoctors/services/doctor_service.dart';

class AddDoctorForm extends StatefulWidget {
  const AddDoctorForm({super.key});

  @override
  State<AddDoctorForm> createState() => _AddDoctorFormState();
}

class _AddDoctorFormState extends State<AddDoctorForm> {
  final _formKey = GlobalKey<FormState>();
  final _doctorService = DoctorService();
  bool _isLoading = false;

  // Controllers
  final _nameController = TextEditingController();
  final _specialtyController = TextEditingController();
  final _ratingController = TextEditingController(text: '4.5');
  final _imageController = TextEditingController(
    text: 'https://i.pravatar.cc/150?img=1',
  );
  final _locationController = TextEditingController();
  final _phoneController = TextEditingController();
  final _experienceController = TextEditingController();
  final _patientsController = TextEditingController(text: '0');
  final _feeController = TextEditingController();
  final _followUpController = TextEditingController(text: '0');
  final _codeController = TextEditingController();
  final _joinedController = TextEditingController(
    text: DateTime.now().year.toString(),
  );
  final _descriptionController = TextEditingController();

  Future<void> _submitForm() async {
    if (_formKey.currentState!.validate()) {
      setState(() => _isLoading = true);

      try {
        final newDoctor = Doctor(
          id: '', // ID will be generated by Firestore
          name: _nameController.text.trim(),
          specialty: _specialtyController.text.trim(),
          rating: double.tryParse(_ratingController.text) ?? 0.0,
          image: _imageController.text.trim(),
          location: _locationController.text.trim(),
          phoneNumber: _phoneController.text.trim(),
          experience: _experienceController.text.trim(),
          patients: int.tryParse(_patientsController.text) ?? 0,
          fee: int.tryParse(_feeController.text) ?? 0,
          followUp: int.tryParse(_followUpController.text) ?? 0,
          code: _codeController.text.trim(),
          joined: _joinedController.text.trim(),
          description: _descriptionController.text.trim(),
        );

        await _doctorService.addDoctor(newDoctor);

        if (mounted) {
          Navigator.pop(context); // Close modal
          ScaffoldMessenger.of(context).showSnackBar(
            const SnackBar(content: Text('Doctor added successfully')),
          );
        }
      } catch (e) {
        if (mounted) {
          ScaffoldMessenger.of(
            context,
          ).showSnackBar(SnackBar(content: Text('Error adding doctor: $e')));
        }
      } finally {
        if (mounted) setState(() => _isLoading = false);
      }
    }
  }

  @override
  void dispose() {
    _nameController.dispose();
    _specialtyController.dispose();
    _ratingController.dispose();
    _imageController.dispose();
    _locationController.dispose();
    _phoneController.dispose();
    _experienceController.dispose();
    _patientsController.dispose();
    _feeController.dispose();
    _followUpController.dispose();
    _codeController.dispose();
    _joinedController.dispose();
    _descriptionController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        color: Color(0xFF1E1E1E),
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(24),
          topRight: Radius.circular(24),
        ),
      ),
      padding: EdgeInsets.only(
        bottom: MediaQuery.of(context).viewInsets.bottom + 20,
        left: 20,
        right: 20,
        top: 20,
      ),
      child: Form(
        key: _formKey,
        child: SingleChildScrollView(
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            mainAxisSize: MainAxisSize.min,
            children: [
              Center(
                child: Container(
                  width: 40,
                  height: 4,
                  decoration: BoxDecoration(
                    color: Colors.grey[600],
                    borderRadius: BorderRadius.circular(2),
                  ),
                ),
              ),
              const SizedBox(height: 20),
              Text(
                'Add New Doctor',
                style: GoogleFonts.inter(
                  fontSize: 20,
                  fontWeight: FontWeight.w600,
                  color: Colors.white,
                ),
              ),
              const SizedBox(height: 20),

              _buildTextField(label: 'Name', controller: _nameController),
              _buildTextField(
                label: 'Specialty',
                controller: _specialtyController,
              ),
              Row(
                children: [
                  Expanded(
                    child: _buildTextField(
                      label: 'Rating',
                      controller: _ratingController,
                      keyboardType: TextInputType.number,
                    ),
                  ),
                  const SizedBox(width: 10),
                  Expanded(
                    child: _buildTextField(
                      label: 'Code',
                      controller: _codeController,
                    ),
                  ),
                ],
              ),
              _buildTextField(label: 'Image URL', controller: _imageController),
              _buildTextField(
                label: 'Location',
                controller: _locationController,
              ),
              _buildTextField(
                label: 'Phone Number',
                controller: _phoneController,
                keyboardType: TextInputType.phone,
              ),
              _buildTextField(
                label: 'Experience',
                controller: _experienceController,
              ),
              Row(
                children: [
                  Expanded(
                    child: _buildTextField(
                      label: 'Fee',
                      controller: _feeController,
                      keyboardType: TextInputType.number,
                    ),
                  ),
                  const SizedBox(width: 10),
                  Expanded(
                    child: _buildTextField(
                      label: 'Follow Up (days)',
                      controller: _followUpController,
                      keyboardType: TextInputType.number,
                    ),
                  ),
                ],
              ),
              _buildTextField(
                label: 'Description',
                controller: _descriptionController,
                maxLines: 3,
              ),

              const SizedBox(height: 24),
              SizedBox(
                width: double.infinity,
                height: 50,
                child: ElevatedButton(
                  onPressed: _isLoading ? null : _submitForm,
                  style: ElevatedButton.styleFrom(
                    backgroundColor: const Color(0xFF57E659),
                    foregroundColor: Colors.black,
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(25),
                    ),
                  ),
                  child: _isLoading
                      ? const SizedBox(
                          width: 20,
                          height: 20,
                          child: CircularProgressIndicator(
                            strokeWidth: 2,
                            color: Colors.black,
                          ),
                        )
                      : Text(
                          'Add Doctor',
                          style: GoogleFonts.inter(
                            fontWeight: FontWeight.w600,
                            fontSize: 16,
                          ),
                        ),
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildTextField({
    required String label,
    required TextEditingController controller,
    TextInputType keyboardType = TextInputType.text,
    int maxLines = 1,
  }) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 16),
      child: TextFormField(
        controller: controller,
        keyboardType: keyboardType,
        maxLines: maxLines,
        style: const TextStyle(color: Colors.white),
        validator: (value) {
          if (value == null || value.isEmpty) {
            return 'Please enter $label';
          }
          return null;
        },
        decoration: InputDecoration(
          labelText: label,
          labelStyle: TextStyle(color: Colors.grey[400]),
          enabledBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: BorderSide(color: Colors.grey[800]!),
          ),
          focusedBorder: OutlineInputBorder(
            borderRadius: BorderRadius.circular(12),
            borderSide: const BorderSide(color: Color(0xFF57E659)),
          ),
          filled: true,
          fillColor: Colors.black.withOpacity(0.3),
        ),
      ),
    );
  }
}
